name: Test

on:
- pull_request
- workflow_dispatch

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out the code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

    - name: Install dependencies for Linux
      run: |
          sudo apt-get update
          sudo apt-get install libfreetype-dev
      if: matrix.os == 'ubuntu-latest'

    - name: Set up uv (with Python ${{ matrix.python-version }})
      uses: astral-sh/setup-uv@v8.1.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Sync dependencies
      run: uv sync --group build
      if: matrix.os == 'ubuntu-latest'

    - name: Sync dependencies (no text rendering)
      run: uv sync --group build --config-setting=setup-args=-Dtext_rendering=false
      if: matrix.os == 'macos-latest'

    - name: Sync dependencies (no text rendering, force MSVC)
      run: >
          uv sync --group build
          --config-setting=setup-args=-Dtext_rendering=false
          --config-setting=setup-args=--vsenv
      if: matrix.os == 'windows-latest'

    - name: Run tests
      run: uv run python -m unittest discover -v celiagg
